---
- hosts: all
  become: true
  tasks:
  - name: remove apache2 package for Debian based distributions
    apt:
      name: 
        - apache2
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]